### ISSUE TITLE
Typo in the default text

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/eucookieconsent#1]
![grafik](https://cloud.githubusercontent.com/assets/318581/26723952/44433594-4797-11e7-88b9-9e5c795ad5fd.png)

This is on the module configuration page. Most likely this should read "Learn more" instead of "Learn Mo**d**e".

**Comment by Dh42** [comment]
Fixed here, https://github.com/thirtybees/eucookieconsent/commit/1a510cd466066ade58f81436191445d8bc42f134
