### ISSUE TITLE
[Feature Request] Make the 'Learn more' link's target attribute optional

### ISSUE THREAD

**Issue by Antagony1060** [thirtybees/eucookieconsent#3]
As it stands the link has the `target="_blank"` attribute, so it always opens in a new tab. This makes the front office inconsistent for internal links.

**Comment by Dh42** [comment]
Unfortunately this cannot be done with the library the module is using. I looked through the docs and examples, I could not find a way to do it. Strange, but it just does not seem like an option.

**Comment by Antagony1060** [comment]
Well thanks for looking into it Lesley. Can you tell me which library it is, please?

**Comment by Dh42** [comment]
Hey, it uses this one, https://www.npmjs.com/package/cookieconsent2

**Comment by Antagony1060** [comment]
Correct me if I'm wrong, but isn't that just a fork of [this](https://github.com/insites/cookieconsent)? And if so won't the solutions outlined in [this discussion](https://github.com/insites/cookieconsent/issues/365) work?
